//// Generated by the protocol buffer compiler.  DO NOT EDIT!
//// NO CHECKED-IN PROTOBUF GENCODE
//// source: app/src/main/java/com/aaron/hookpractice/protocbuf/user.proto
//// Protobuf Java Version: 4.28.2
//
//package com.aaron.hookpractice.generate;
//
//public final class UserOuterClass {
//  private UserOuterClass() {}
//  static {
//    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
//      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
//      /* major= */ 4,
//      /* minor= */ 28,
//      /* patch= */ 2,
//      /* suffix= */ "",
//      UserOuterClass.class.getName());
//  }
//  public static void registerAllExtensions(
//      com.google.protobuf.ExtensionRegistryLite registry) {
//  }
//
//  public static void registerAllExtensions(
//      com.google.protobuf.ExtensionRegistry registry) {
//    registerAllExtensions(
//        (com.google.protobuf.ExtensionRegistryLite) registry);
//  }
//  /**
//   * Protobuf enum {@code com.aaron.hookpractice.generate.Gender}
//   */
//  public enum Gender
//      implements com.google.protobuf.ProtocolMessageEnum {
//    /**
//     * <code>Male = 0;</code>
//     */
//    Male(0),
//    /**
//     * <code>Female = 1;</code>
//     */
//    Female(1),
//    UNRECOGNIZED(-1),
//    ;
//
//    static {
//      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
//        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
//        /* major= */ 4,
//        /* minor= */ 28,
//        /* patch= */ 2,
//        /* suffix= */ "",
//        Gender.class.getName());
//    }
//    /**
//     * <code>Male = 0;</code>
//     */
//    public static final int Male_VALUE = 0;
//    /**
//     * <code>Female = 1;</code>
//     */
//    public static final int Female_VALUE = 1;
//
//
//    public final int getNumber() {
//      if (this == UNRECOGNIZED) {
//        throw new java.lang.IllegalArgumentException(
//            "Can't get the number of an unknown enum value.");
//      }
//      return value;
//    }
//
//    /**
//     * @param value The numeric wire value of the corresponding enum entry.
//     * @return The enum associated with the given numeric wire value.
//     * @deprecated Use {@link #forNumber(int)} instead.
//     */
//    @java.lang.Deprecated
//    public static Gender valueOf(int value) {
//      return forNumber(value);
//    }
//
//    /**
//     * @param value The numeric wire value of the corresponding enum entry.
//     * @return The enum associated with the given numeric wire value.
//     */
//    public static Gender forNumber(int value) {
//      switch (value) {
//        case 0: return Male;
//        case 1: return Female;
//        default: return null;
//      }
//    }
//
//    public static com.google.protobuf.Internal.EnumLiteMap<Gender>
//        internalGetValueMap() {
//      return internalValueMap;
//    }
//    private static final com.google.protobuf.Internal.EnumLiteMap<
//        Gender> internalValueMap =
//          new com.google.protobuf.Internal.EnumLiteMap<Gender>() {
//            public Gender findValueByNumber(int number) {
//              return Gender.forNumber(number);
//            }
//          };
//
//    public final com.google.protobuf.Descriptors.EnumValueDescriptor
//        getValueDescriptor() {
//      if (this == UNRECOGNIZED) {
//        throw new java.lang.IllegalStateException(
//            "Can't get the descriptor of an unrecognized enum value.");
//      }
//      return getDescriptor().getValues().get(ordinal());
//    }
//    public final com.google.protobuf.Descriptors.EnumDescriptor
//        getDescriptorForType() {
//      return getDescriptor();
//    }
//    public static final com.google.protobuf.Descriptors.EnumDescriptor
//        getDescriptor() {
//      return com.aaron.hookpractice.generate.UserOuterClass.getDescriptor().getEnumTypes().get(0);
//    }
//
//    private static final Gender[] VALUES = values();
//
//    public static Gender valueOf(
//        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
//      if (desc.getType() != getDescriptor()) {
//        throw new java.lang.IllegalArgumentException(
//          "EnumValueDescriptor is not for this type.");
//      }
//      if (desc.getIndex() == -1) {
//        return UNRECOGNIZED;
//      }
//      return VALUES[desc.getIndex()];
//    }
//
//    private final int value;
//
//    private Gender(int value) {
//      this.value = value;
//    }
//
//    // @@protoc_insertion_point(enum_scope:com.aaron.hookpractice.generate.Gender)
//  }
//
//  public interface UserOrBuilder extends
//      // @@protoc_insertion_point(interface_extends:com.aaron.hookpractice.generate.User)
//      com.google.protobuf.MessageOrBuilder {
//
//    /**
//     * <code>int64 id = 1;</code>
//     * @return The id.
//     */
//    long getId();
//
//    /**
//     * <code>string name = 2;</code>
//     * @return The name.
//     */
//    java.lang.String getName();
//    /**
//     * <code>string name = 2;</code>
//     * @return The bytes for name.
//     */
//    com.google.protobuf.ByteString
//        getNameBytes();
//
//    /**
//     * <code>optional .com.aaron.hookpractice.generate.Gender gender = 3;</code>
//     * @return Whether the gender field is set.
//     */
//    boolean hasGender();
//    /**
//     * <code>optional .com.aaron.hookpractice.generate.Gender gender = 3;</code>
//     * @return The enum numeric value on the wire for gender.
//     */
//    int getGenderValue();
//    /**
//     * <code>optional .com.aaron.hookpractice.generate.Gender gender = 3;</code>
//     * @return The gender.
//     */
//    com.aaron.hookpractice.generate.UserOuterClass.Gender getGender();
//
//    /**
//     * <code>optional .com.aaron.hookpractice.generate.Address address = 4;</code>
//     * @return Whether the address field is set.
//     */
//    boolean hasAddress();
//    /**
//     * <code>optional .com.aaron.hookpractice.generate.Address address = 4;</code>
//     * @return The address.
//     */
//    com.aaron.hookpractice.generate.UserOuterClass.Address getAddress();
//    /**
//     * <code>optional .com.aaron.hookpractice.generate.Address address = 4;</code>
//     */
//    com.aaron.hookpractice.generate.UserOuterClass.AddressOrBuilder getAddressOrBuilder();
//  }
//  /**
//   * Protobuf type {@code com.aaron.hookpractice.generate.User}
//   */
//  public static final class User extends
//      com.google.protobuf.GeneratedMessage implements
//      // @@protoc_insertion_point(message_implements:com.aaron.hookpractice.generate.User)
//      UserOrBuilder {
//  private static final long serialVersionUID = 0L;
//    static {
//      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
//        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
//        /* major= */ 4,
//        /* minor= */ 28,
//        /* patch= */ 2,
//        /* suffix= */ "",
//        User.class.getName());
//    }
//    // Use User.newBuilder() to construct.
//    private User(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
//      super(builder);
//    }
//    private User() {
//      name_ = "";
//      gender_ = 0;
//    }
//
//    public static final com.google.protobuf.Descriptors.Descriptor
//        getDescriptor() {
//      return com.aaron.hookpractice.generate.UserOuterClass.internal_static_com_aaron_hookpractice_generate_User_descriptor;
//    }
//
//    @java.lang.Override
//    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
//        internalGetFieldAccessorTable() {
//      return com.aaron.hookpractice.generate.UserOuterClass.internal_static_com_aaron_hookpractice_generate_User_fieldAccessorTable
//          .ensureFieldAccessorsInitialized(
//              com.aaron.hookpractice.generate.UserOuterClass.User.class, com.aaron.hookpractice.generate.UserOuterClass.User.Builder.class);
//    }
//
//    private int bitField0_;
//    public static final int ID_FIELD_NUMBER = 1;
//    private long id_ = 0L;
//    /**
//     * <code>int64 id = 1;</code>
//     * @return The id.
//     */
//    @java.lang.Override
//    public long getId() {
//      return id_;
//    }
//
//    public static final int NAME_FIELD_NUMBER = 2;
//    @SuppressWarnings("serial")
//    private volatile java.lang.Object name_ = "";
//    /**
//     * <code>string name = 2;</code>
//     * @return The name.
//     */
//    @java.lang.Override
//    public java.lang.String getName() {
//      java.lang.Object ref = name_;
//      if (ref instanceof java.lang.String) {
//        return (java.lang.String) ref;
//      } else {
//        com.google.protobuf.ByteString bs =
//            (com.google.protobuf.ByteString) ref;
//        java.lang.String s = bs.toStringUtf8();
//        name_ = s;
//        return s;
//      }
//    }
//    /**
//     * <code>string name = 2;</code>
//     * @return The bytes for name.
//     */
//    @java.lang.Override
//    public com.google.protobuf.ByteString
//        getNameBytes() {
//      java.lang.Object ref = name_;
//      if (ref instanceof java.lang.String) {
//        com.google.protobuf.ByteString b =
//            com.google.protobuf.ByteString.copyFromUtf8(
//                (java.lang.String) ref);
//        name_ = b;
//        return b;
//      } else {
//        return (com.google.protobuf.ByteString) ref;
//      }
//    }
//
//    public static final int GENDER_FIELD_NUMBER = 3;
//    private int gender_ = 0;
//    /**
//     * <code>optional .com.aaron.hookpractice.generate.Gender gender = 3;</code>
//     * @return Whether the gender field is set.
//     */
//    @java.lang.Override public boolean hasGender() {
//      return ((bitField0_ & 0x00000001) != 0);
//    }
//    /**
//     * <code>optional .com.aaron.hookpractice.generate.Gender gender = 3;</code>
//     * @return The enum numeric value on the wire for gender.
//     */
//    @java.lang.Override public int getGenderValue() {
//      return gender_;
//    }
//    /**
//     * <code>optional .com.aaron.hookpractice.generate.Gender gender = 3;</code>
//     * @return The gender.
//     */
//    @java.lang.Override public com.aaron.hookpractice.generate.UserOuterClass.Gender getGender() {
//      com.aaron.hookpractice.generate.UserOuterClass.Gender result = com.aaron.hookpractice.generate.UserOuterClass.Gender.forNumber(gender_);
//      return result == null ? com.aaron.hookpractice.generate.UserOuterClass.Gender.UNRECOGNIZED : result;
//    }
//
//    public static final int ADDRESS_FIELD_NUMBER = 4;
//    private com.aaron.hookpractice.generate.UserOuterClass.Address address_;
//    /**
//     * <code>optional .com.aaron.hookpractice.generate.Address address = 4;</code>
//     * @return Whether the address field is set.
//     */
//    @java.lang.Override
//    public boolean hasAddress() {
//      return ((bitField0_ & 0x00000002) != 0);
//    }
//    /**
//     * <code>optional .com.aaron.hookpractice.generate.Address address = 4;</code>
//     * @return The address.
//     */
//    @java.lang.Override
//    public com.aaron.hookpractice.generate.UserOuterClass.Address getAddress() {
//      return address_ == null ? com.aaron.hookpractice.generate.UserOuterClass.Address.getDefaultInstance() : address_;
//    }
//    /**
//     * <code>optional .com.aaron.hookpractice.generate.Address address = 4;</code>
//     */
//    @java.lang.Override
//    public com.aaron.hookpractice.generate.UserOuterClass.AddressOrBuilder getAddressOrBuilder() {
//      return address_ == null ? com.aaron.hookpractice.generate.UserOuterClass.Address.getDefaultInstance() : address_;
//    }
//
//    private byte memoizedIsInitialized = -1;
//    @java.lang.Override
//    public final boolean isInitialized() {
//      byte isInitialized = memoizedIsInitialized;
//      if (isInitialized == 1) return true;
//      if (isInitialized == 0) return false;
//
//      memoizedIsInitialized = 1;
//      return true;
//    }
//
//    @java.lang.Override
//    public void writeTo(com.google.protobuf.CodedOutputStream output)
//                        throws java.io.IOException {
//      if (id_ != 0L) {
//        output.writeInt64(1, id_);
//      }
//      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
//        com.google.protobuf.GeneratedMessage.writeString(output, 2, name_);
//      }
//      if (((bitField0_ & 0x00000001) != 0)) {
//        output.writeEnum(3, gender_);
//      }
//      if (((bitField0_ & 0x00000002) != 0)) {
//        output.writeMessage(4, getAddress());
//      }
//      getUnknownFields().writeTo(output);
//    }
//
//    @java.lang.Override
//    public int getSerializedSize() {
//      int size = memoizedSize;
//      if (size != -1) return size;
//
//      size = 0;
//      if (id_ != 0L) {
//        size += com.google.protobuf.CodedOutputStream
//          .computeInt64Size(1, id_);
//      }
//      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
//        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, name_);
//      }
//      if (((bitField0_ & 0x00000001) != 0)) {
//        size += com.google.protobuf.CodedOutputStream
//          .computeEnumSize(3, gender_);
//      }
//      if (((bitField0_ & 0x00000002) != 0)) {
//        size += com.google.protobuf.CodedOutputStream
//          .computeMessageSize(4, getAddress());
//      }
//      size += getUnknownFields().getSerializedSize();
//      memoizedSize = size;
//      return size;
//    }
//
//    @java.lang.Override
//    public boolean equals(final java.lang.Object obj) {
//      if (obj == this) {
//       return true;
//      }
//      if (!(obj instanceof com.aaron.hookpractice.generate.UserOuterClass.User)) {
//        return super.equals(obj);
//      }
//      com.aaron.hookpractice.generate.UserOuterClass.User other = (com.aaron.hookpractice.generate.UserOuterClass.User) obj;
//
//      if (getId()
//          != other.getId()) return false;
//      if (!getName()
//          .equals(other.getName())) return false;
//      if (hasGender() != other.hasGender()) return false;
//      if (hasGender()) {
//        if (gender_ != other.gender_) return false;
//      }
//      if (hasAddress() != other.hasAddress()) return false;
//      if (hasAddress()) {
//        if (!getAddress()
//            .equals(other.getAddress())) return false;
//      }
//      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
//      return true;
//    }
//
//    @java.lang.Override
//    public int hashCode() {
//      if (memoizedHashCode != 0) {
//        return memoizedHashCode;
//      }
//      int hash = 41;
//      hash = (19 * hash) + getDescriptor().hashCode();
//      hash = (37 * hash) + ID_FIELD_NUMBER;
//      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
//          getId());
//      hash = (37 * hash) + NAME_FIELD_NUMBER;
//      hash = (53 * hash) + getName().hashCode();
//      if (hasGender()) {
//        hash = (37 * hash) + GENDER_FIELD_NUMBER;
//        hash = (53 * hash) + gender_;
//      }
//      if (hasAddress()) {
//        hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
//        hash = (53 * hash) + getAddress().hashCode();
//      }
//      hash = (29 * hash) + getUnknownFields().hashCode();
//      memoizedHashCode = hash;
//      return hash;
//    }
//
//    public static com.aaron.hookpractice.generate.UserOuterClass.User parseFrom(
//        java.nio.ByteBuffer data)
//        throws com.google.protobuf.InvalidProtocolBufferException {
//      return PARSER.parseFrom(data);
//    }
//    public static com.aaron.hookpractice.generate.UserOuterClass.User parseFrom(
//        java.nio.ByteBuffer data,
//        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//        throws com.google.protobuf.InvalidProtocolBufferException {
//      return PARSER.parseFrom(data, extensionRegistry);
//    }
//    public static com.aaron.hookpractice.generate.UserOuterClass.User parseFrom(
//        com.google.protobuf.ByteString data)
//        throws com.google.protobuf.InvalidProtocolBufferException {
//      return PARSER.parseFrom(data);
//    }
//    public static com.aaron.hookpractice.generate.UserOuterClass.User parseFrom(
//        com.google.protobuf.ByteString data,
//        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//        throws com.google.protobuf.InvalidProtocolBufferException {
//      return PARSER.parseFrom(data, extensionRegistry);
//    }
//    public static com.aaron.hookpractice.generate.UserOuterClass.User parseFrom(byte[] data)
//        throws com.google.protobuf.InvalidProtocolBufferException {
//      return PARSER.parseFrom(data);
//    }
//    public static com.aaron.hookpractice.generate.UserOuterClass.User parseFrom(
//        byte[] data,
//        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//        throws com.google.protobuf.InvalidProtocolBufferException {
//      return PARSER.parseFrom(data, extensionRegistry);
//    }
//    public static com.aaron.hookpractice.generate.UserOuterClass.User parseFrom(java.io.InputStream input)
//        throws java.io.IOException {
//      return com.google.protobuf.GeneratedMessage
//          .parseWithIOException(PARSER, input);
//    }
//    public static com.aaron.hookpractice.generate.UserOuterClass.User parseFrom(
//        java.io.InputStream input,
//        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//        throws java.io.IOException {
//      return com.google.protobuf.GeneratedMessage
//          .parseWithIOException(PARSER, input, extensionRegistry);
//    }
//
//    public static com.aaron.hookpractice.generate.UserOuterClass.User parseDelimitedFrom(java.io.InputStream input)
//        throws java.io.IOException {
//      return com.google.protobuf.GeneratedMessage
//          .parseDelimitedWithIOException(PARSER, input);
//    }
//
//    public static com.aaron.hookpractice.generate.UserOuterClass.User parseDelimitedFrom(
//        java.io.InputStream input,
//        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//        throws java.io.IOException {
//      return com.google.protobuf.GeneratedMessage
//          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
//    }
//    public static com.aaron.hookpractice.generate.UserOuterClass.User parseFrom(
//        com.google.protobuf.CodedInputStream input)
//        throws java.io.IOException {
//      return com.google.protobuf.GeneratedMessage
//          .parseWithIOException(PARSER, input);
//    }
//    public static com.aaron.hookpractice.generate.UserOuterClass.User parseFrom(
//        com.google.protobuf.CodedInputStream input,
//        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//        throws java.io.IOException {
//      return com.google.protobuf.GeneratedMessage
//          .parseWithIOException(PARSER, input, extensionRegistry);
//    }
//
//    @java.lang.Override
//    public Builder newBuilderForType() { return newBuilder(); }
//    public static Builder newBuilder() {
//      return DEFAULT_INSTANCE.toBuilder();
//    }
//    public static Builder newBuilder(com.aaron.hookpractice.generate.UserOuterClass.User prototype) {
//      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
//    }
//    @java.lang.Override
//    public Builder toBuilder() {
//      return this == DEFAULT_INSTANCE
//          ? new Builder() : new Builder().mergeFrom(this);
//    }
//
//    @java.lang.Override
//    protected Builder newBuilderForType(
//        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
//      Builder builder = new Builder(parent);
//      return builder;
//    }
//    /**
//     * Protobuf type {@code com.aaron.hookpractice.generate.User}
//     */
//    public static final class Builder extends
//        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
//        // @@protoc_insertion_point(builder_implements:com.aaron.hookpractice.generate.User)
//        com.aaron.hookpractice.generate.UserOuterClass.UserOrBuilder {
//      public static final com.google.protobuf.Descriptors.Descriptor
//          getDescriptor() {
//        return com.aaron.hookpractice.generate.UserOuterClass.internal_static_com_aaron_hookpractice_generate_User_descriptor;
//      }
//
//      @java.lang.Override
//      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
//          internalGetFieldAccessorTable() {
//        return com.aaron.hookpractice.generate.UserOuterClass.internal_static_com_aaron_hookpractice_generate_User_fieldAccessorTable
//            .ensureFieldAccessorsInitialized(
//                com.aaron.hookpractice.generate.UserOuterClass.User.class, com.aaron.hookpractice.generate.UserOuterClass.User.Builder.class);
//      }
//
//      // Construct using com.aaron.hookpractice.generate.UserOuterClass.User.newBuilder()
//      private Builder() {
//        maybeForceBuilderInitialization();
//      }
//
//      private Builder(
//          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
//        super(parent);
//        maybeForceBuilderInitialization();
//      }
//      private void maybeForceBuilderInitialization() {
//        if (com.google.protobuf.GeneratedMessage
//                .alwaysUseFieldBuilders) {
//          getAddressFieldBuilder();
//        }
//      }
//      @java.lang.Override
//      public Builder clear() {
//        super.clear();
//        bitField0_ = 0;
//        id_ = 0L;
//        name_ = "";
//        gender_ = 0;
//        address_ = null;
//        if (addressBuilder_ != null) {
//          addressBuilder_.dispose();
//          addressBuilder_ = null;
//        }
//        return this;
//      }
//
//      @java.lang.Override
//      public com.google.protobuf.Descriptors.Descriptor
//          getDescriptorForType() {
//        return com.aaron.hookpractice.generate.UserOuterClass.internal_static_com_aaron_hookpractice_generate_User_descriptor;
//      }
//
//      @java.lang.Override
//      public com.aaron.hookpractice.generate.UserOuterClass.User getDefaultInstanceForType() {
//        return com.aaron.hookpractice.generate.UserOuterClass.User.getDefaultInstance();
//      }
//
//      @java.lang.Override
//      public com.aaron.hookpractice.generate.UserOuterClass.User build() {
//        com.aaron.hookpractice.generate.UserOuterClass.User result = buildPartial();
//        if (!result.isInitialized()) {
//          throw newUninitializedMessageException(result);
//        }
//        return result;
//      }
//
//      @java.lang.Override
//      public com.aaron.hookpractice.generate.UserOuterClass.User buildPartial() {
//        com.aaron.hookpractice.generate.UserOuterClass.User result = new com.aaron.hookpractice.generate.UserOuterClass.User(this);
//        if (bitField0_ != 0) { buildPartial0(result); }
//        onBuilt();
//        return result;
//      }
//
//      private void buildPartial0(com.aaron.hookpractice.generate.UserOuterClass.User result) {
//        int from_bitField0_ = bitField0_;
//        if (((from_bitField0_ & 0x00000001) != 0)) {
//          result.id_ = id_;
//        }
//        if (((from_bitField0_ & 0x00000002) != 0)) {
//          result.name_ = name_;
//        }
//        int to_bitField0_ = 0;
//        if (((from_bitField0_ & 0x00000004) != 0)) {
//          result.gender_ = gender_;
//          to_bitField0_ |= 0x00000001;
//        }
//        if (((from_bitField0_ & 0x00000008) != 0)) {
//          result.address_ = addressBuilder_ == null
//              ? address_
//              : addressBuilder_.build();
//          to_bitField0_ |= 0x00000002;
//        }
//        result.bitField0_ |= to_bitField0_;
//      }
//
//      @java.lang.Override
//      public Builder mergeFrom(com.google.protobuf.Message other) {
//        if (other instanceof com.aaron.hookpractice.generate.UserOuterClass.User) {
//          return mergeFrom((com.aaron.hookpractice.generate.UserOuterClass.User)other);
//        } else {
//          super.mergeFrom(other);
//          return this;
//        }
//      }
//
//      public Builder mergeFrom(com.aaron.hookpractice.generate.UserOuterClass.User other) {
//        if (other == com.aaron.hookpractice.generate.UserOuterClass.User.getDefaultInstance()) return this;
//        if (other.getId() != 0L) {
//          setId(other.getId());
//        }
//        if (!other.getName().isEmpty()) {
//          name_ = other.name_;
//          bitField0_ |= 0x00000002;
//          onChanged();
//        }
//        if (other.hasGender()) {
//          setGender(other.getGender());
//        }
//        if (other.hasAddress()) {
//          mergeAddress(other.getAddress());
//        }
//        this.mergeUnknownFields(other.getUnknownFields());
//        onChanged();
//        return this;
//      }
//
//      @java.lang.Override
//      public final boolean isInitialized() {
//        return true;
//      }
//
//      @java.lang.Override
//      public Builder mergeFrom(
//          com.google.protobuf.CodedInputStream input,
//          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//          throws java.io.IOException {
//        if (extensionRegistry == null) {
//          throw new java.lang.NullPointerException();
//        }
//        try {
//          boolean done = false;
//          while (!done) {
//            int tag = input.readTag();
//            switch (tag) {
//              case 0:
//                done = true;
//                break;
//              case 8: {
//                id_ = input.readInt64();
//                bitField0_ |= 0x00000001;
//                break;
//              } // case 8
//              case 18: {
//                name_ = input.readStringRequireUtf8();
//                bitField0_ |= 0x00000002;
//                break;
//              } // case 18
//              case 24: {
//                gender_ = input.readEnum();
//                bitField0_ |= 0x00000004;
//                break;
//              } // case 24
//              case 34: {
//                input.readMessage(
//                    getAddressFieldBuilder().getBuilder(),
//                    extensionRegistry);
//                bitField0_ |= 0x00000008;
//                break;
//              } // case 34
//              default: {
//                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
//                  done = true; // was an endgroup tag
//                }
//                break;
//              } // default:
//            } // switch (tag)
//          } // while (!done)
//        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
//          throw e.unwrapIOException();
//        } finally {
//          onChanged();
//        } // finally
//        return this;
//      }
//      private int bitField0_;
//
//      private long id_ ;
//      /**
//       * <code>int64 id = 1;</code>
//       * @return The id.
//       */
//      @java.lang.Override
//      public long getId() {
//        return id_;
//      }
//      /**
//       * <code>int64 id = 1;</code>
//       * @param value The id to set.
//       * @return This builder for chaining.
//       */
//      public Builder setId(long value) {
//
//        id_ = value;
//        bitField0_ |= 0x00000001;
//        onChanged();
//        return this;
//      }
//      /**
//       * <code>int64 id = 1;</code>
//       * @return This builder for chaining.
//       */
//      public Builder clearId() {
//        bitField0_ = (bitField0_ & ~0x00000001);
//        id_ = 0L;
//        onChanged();
//        return this;
//      }
//
//      private java.lang.Object name_ = "";
//      /**
//       * <code>string name = 2;</code>
//       * @return The name.
//       */
//      public java.lang.String getName() {
//        java.lang.Object ref = name_;
//        if (!(ref instanceof java.lang.String)) {
//          com.google.protobuf.ByteString bs =
//              (com.google.protobuf.ByteString) ref;
//          java.lang.String s = bs.toStringUtf8();
//          name_ = s;
//          return s;
//        } else {
//          return (java.lang.String) ref;
//        }
//      }
//      /**
//       * <code>string name = 2;</code>
//       * @return The bytes for name.
//       */
//      public com.google.protobuf.ByteString
//          getNameBytes() {
//        java.lang.Object ref = name_;
//        if (ref instanceof String) {
//          com.google.protobuf.ByteString b =
//              com.google.protobuf.ByteString.copyFromUtf8(
//                  (java.lang.String) ref);
//          name_ = b;
//          return b;
//        } else {
//          return (com.google.protobuf.ByteString) ref;
//        }
//      }
//      /**
//       * <code>string name = 2;</code>
//       * @param value The name to set.
//       * @return This builder for chaining.
//       */
//      public Builder setName(
//          java.lang.String value) {
//        if (value == null) { throw new NullPointerException(); }
//        name_ = value;
//        bitField0_ |= 0x00000002;
//        onChanged();
//        return this;
//      }
//      /**
//       * <code>string name = 2;</code>
//       * @return This builder for chaining.
//       */
//      public Builder clearName() {
//        name_ = getDefaultInstance().getName();
//        bitField0_ = (bitField0_ & ~0x00000002);
//        onChanged();
//        return this;
//      }
//      /**
//       * <code>string name = 2;</code>
//       * @param value The bytes for name to set.
//       * @return This builder for chaining.
//       */
//      public Builder setNameBytes(
//          com.google.protobuf.ByteString value) {
//        if (value == null) { throw new NullPointerException(); }
//        checkByteStringIsUtf8(value);
//        name_ = value;
//        bitField0_ |= 0x00000002;
//        onChanged();
//        return this;
//      }
//
//      private int gender_ = 0;
//      /**
//       * <code>optional .com.aaron.hookpractice.generate.Gender gender = 3;</code>
//       * @return Whether the gender field is set.
//       */
//      @java.lang.Override public boolean hasGender() {
//        return ((bitField0_ & 0x00000004) != 0);
//      }
//      /**
//       * <code>optional .com.aaron.hookpractice.generate.Gender gender = 3;</code>
//       * @return The enum numeric value on the wire for gender.
//       */
//      @java.lang.Override public int getGenderValue() {
//        return gender_;
//      }
//      /**
//       * <code>optional .com.aaron.hookpractice.generate.Gender gender = 3;</code>
//       * @param value The enum numeric value on the wire for gender to set.
//       * @return This builder for chaining.
//       */
//      public Builder setGenderValue(int value) {
//        gender_ = value;
//        bitField0_ |= 0x00000004;
//        onChanged();
//        return this;
//      }
//      /**
//       * <code>optional .com.aaron.hookpractice.generate.Gender gender = 3;</code>
//       * @return The gender.
//       */
//      @java.lang.Override
//      public com.aaron.hookpractice.generate.UserOuterClass.Gender getGender() {
//        com.aaron.hookpractice.generate.UserOuterClass.Gender result = com.aaron.hookpractice.generate.UserOuterClass.Gender.forNumber(gender_);
//        return result == null ? com.aaron.hookpractice.generate.UserOuterClass.Gender.UNRECOGNIZED : result;
//      }
//      /**
//       * <code>optional .com.aaron.hookpractice.generate.Gender gender = 3;</code>
//       * @param value The gender to set.
//       * @return This builder for chaining.
//       */
//      public Builder setGender(com.aaron.hookpractice.generate.UserOuterClass.Gender value) {
//        if (value == null) {
//          throw new NullPointerException();
//        }
//        bitField0_ |= 0x00000004;
//        gender_ = value.getNumber();
//        onChanged();
//        return this;
//      }
//      /**
//       * <code>optional .com.aaron.hookpractice.generate.Gender gender = 3;</code>
//       * @return This builder for chaining.
//       */
//      public Builder clearGender() {
//        bitField0_ = (bitField0_ & ~0x00000004);
//        gender_ = 0;
//        onChanged();
//        return this;
//      }
//
//      private com.aaron.hookpractice.generate.UserOuterClass.Address address_;
//      private com.google.protobuf.SingleFieldBuilder<
//          com.aaron.hookpractice.generate.UserOuterClass.Address, com.aaron.hookpractice.generate.UserOuterClass.Address.Builder, com.aaron.hookpractice.generate.UserOuterClass.AddressOrBuilder> addressBuilder_;
//      /**
//       * <code>optional .com.aaron.hookpractice.generate.Address address = 4;</code>
//       * @return Whether the address field is set.
//       */
//      public boolean hasAddress() {
//        return ((bitField0_ & 0x00000008) != 0);
//      }
//      /**
//       * <code>optional .com.aaron.hookpractice.generate.Address address = 4;</code>
//       * @return The address.
//       */
//      public com.aaron.hookpractice.generate.UserOuterClass.Address getAddress() {
//        if (addressBuilder_ == null) {
//          return address_ == null ? com.aaron.hookpractice.generate.UserOuterClass.Address.getDefaultInstance() : address_;
//        } else {
//          return addressBuilder_.getMessage();
//        }
//      }
//      /**
//       * <code>optional .com.aaron.hookpractice.generate.Address address = 4;</code>
//       */
//      public Builder setAddress(com.aaron.hookpractice.generate.UserOuterClass.Address value) {
//        if (addressBuilder_ == null) {
//          if (value == null) {
//            throw new NullPointerException();
//          }
//          address_ = value;
//        } else {
//          addressBuilder_.setMessage(value);
//        }
//        bitField0_ |= 0x00000008;
//        onChanged();
//        return this;
//      }
//      /**
//       * <code>optional .com.aaron.hookpractice.generate.Address address = 4;</code>
//       */
//      public Builder setAddress(
//          com.aaron.hookpractice.generate.UserOuterClass.Address.Builder builderForValue) {
//        if (addressBuilder_ == null) {
//          address_ = builderForValue.build();
//        } else {
//          addressBuilder_.setMessage(builderForValue.build());
//        }
//        bitField0_ |= 0x00000008;
//        onChanged();
//        return this;
//      }
//      /**
//       * <code>optional .com.aaron.hookpractice.generate.Address address = 4;</code>
//       */
//      public Builder mergeAddress(com.aaron.hookpractice.generate.UserOuterClass.Address value) {
//        if (addressBuilder_ == null) {
//          if (((bitField0_ & 0x00000008) != 0) &&
//            address_ != null &&
//            address_ != com.aaron.hookpractice.generate.UserOuterClass.Address.getDefaultInstance()) {
//            getAddressBuilder().mergeFrom(value);
//          } else {
//            address_ = value;
//          }
//        } else {
//          addressBuilder_.mergeFrom(value);
//        }
//        if (address_ != null) {
//          bitField0_ |= 0x00000008;
//          onChanged();
//        }
//        return this;
//      }
//      /**
//       * <code>optional .com.aaron.hookpractice.generate.Address address = 4;</code>
//       */
//      public Builder clearAddress() {
//        bitField0_ = (bitField0_ & ~0x00000008);
//        address_ = null;
//        if (addressBuilder_ != null) {
//          addressBuilder_.dispose();
//          addressBuilder_ = null;
//        }
//        onChanged();
//        return this;
//      }
//      /**
//       * <code>optional .com.aaron.hookpractice.generate.Address address = 4;</code>
//       */
//      public com.aaron.hookpractice.generate.UserOuterClass.Address.Builder getAddressBuilder() {
//        bitField0_ |= 0x00000008;
//        onChanged();
//        return getAddressFieldBuilder().getBuilder();
//      }
//      /**
//       * <code>optional .com.aaron.hookpractice.generate.Address address = 4;</code>
//       */
//      public com.aaron.hookpractice.generate.UserOuterClass.AddressOrBuilder getAddressOrBuilder() {
//        if (addressBuilder_ != null) {
//          return addressBuilder_.getMessageOrBuilder();
//        } else {
//          return address_ == null ?
//              com.aaron.hookpractice.generate.UserOuterClass.Address.getDefaultInstance() : address_;
//        }
//      }
//      /**
//       * <code>optional .com.aaron.hookpractice.generate.Address address = 4;</code>
//       */
//      private com.google.protobuf.SingleFieldBuilder<
//          com.aaron.hookpractice.generate.UserOuterClass.Address, com.aaron.hookpractice.generate.UserOuterClass.Address.Builder, com.aaron.hookpractice.generate.UserOuterClass.AddressOrBuilder>
//          getAddressFieldBuilder() {
//        if (addressBuilder_ == null) {
//          addressBuilder_ = new com.google.protobuf.SingleFieldBuilder<
//              com.aaron.hookpractice.generate.UserOuterClass.Address, com.aaron.hookpractice.generate.UserOuterClass.Address.Builder, com.aaron.hookpractice.generate.UserOuterClass.AddressOrBuilder>(
//                  getAddress(),
//                  getParentForChildren(),
//                  isClean());
//          address_ = null;
//        }
//        return addressBuilder_;
//      }
//
//      // @@protoc_insertion_point(builder_scope:com.aaron.hookpractice.generate.User)
//    }
//
//    // @@protoc_insertion_point(class_scope:com.aaron.hookpractice.generate.User)
//    private static final com.aaron.hookpractice.generate.UserOuterClass.User DEFAULT_INSTANCE;
//    static {
//      DEFAULT_INSTANCE = new com.aaron.hookpractice.generate.UserOuterClass.User();
//    }
//
//    public static com.aaron.hookpractice.generate.UserOuterClass.User getDefaultInstance() {
//      return DEFAULT_INSTANCE;
//    }
//
//    private static final com.google.protobuf.Parser<User>
//        PARSER = new com.google.protobuf.AbstractParser<User>() {
//      @java.lang.Override
//      public User parsePartialFrom(
//          com.google.protobuf.CodedInputStream input,
//          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//          throws com.google.protobuf.InvalidProtocolBufferException {
//        Builder builder = newBuilder();
//        try {
//          builder.mergeFrom(input, extensionRegistry);
//        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
//          throw e.setUnfinishedMessage(builder.buildPartial());
//        } catch (com.google.protobuf.UninitializedMessageException e) {
//          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
//        } catch (java.io.IOException e) {
//          throw new com.google.protobuf.InvalidProtocolBufferException(e)
//              .setUnfinishedMessage(builder.buildPartial());
//        }
//        return builder.buildPartial();
//      }
//    };
//
//    public static com.google.protobuf.Parser<User> parser() {
//      return PARSER;
//    }
//
//    @java.lang.Override
//    public com.google.protobuf.Parser<User> getParserForType() {
//      return PARSER;
//    }
//
//    @java.lang.Override
//    public com.aaron.hookpractice.generate.UserOuterClass.User getDefaultInstanceForType() {
//      return DEFAULT_INSTANCE;
//    }
//
//  }
//
//  public interface AddressOrBuilder extends
//      // @@protoc_insertion_point(interface_extends:com.aaron.hookpractice.generate.Address)
//      com.google.protobuf.MessageOrBuilder {
//
//    /**
//     * <code>string province = 1;</code>
//     * @return The province.
//     */
//    java.lang.String getProvince();
//    /**
//     * <code>string province = 1;</code>
//     * @return The bytes for province.
//     */
//    com.google.protobuf.ByteString
//        getProvinceBytes();
//
//    /**
//     * <code>string city = 2;</code>
//     * @return The city.
//     */
//    java.lang.String getCity();
//    /**
//     * <code>string city = 2;</code>
//     * @return The bytes for city.
//     */
//    com.google.protobuf.ByteString
//        getCityBytes();
//
//    /**
//     * <code>optional string district = 3;</code>
//     * @return Whether the district field is set.
//     */
//    boolean hasDistrict();
//    /**
//     * <code>optional string district = 3;</code>
//     * @return The district.
//     */
//    java.lang.String getDistrict();
//    /**
//     * <code>optional string district = 3;</code>
//     * @return The bytes for district.
//     */
//    com.google.protobuf.ByteString
//        getDistrictBytes();
//
//    /**
//     * <code>optional string street = 4;</code>
//     * @return Whether the street field is set.
//     */
//    boolean hasStreet();
//    /**
//     * <code>optional string street = 4;</code>
//     * @return The street.
//     */
//    java.lang.String getStreet();
//    /**
//     * <code>optional string street = 4;</code>
//     * @return The bytes for street.
//     */
//    com.google.protobuf.ByteString
//        getStreetBytes();
//
//    /**
//     * <code>string address = 5;</code>
//     * @return The address.
//     */
//    java.lang.String getAddress();
//    /**
//     * <code>string address = 5;</code>
//     * @return The bytes for address.
//     */
//    com.google.protobuf.ByteString
//        getAddressBytes();
//  }
//  /**
//   * Protobuf type {@code com.aaron.hookpractice.generate.Address}
//   */
//  public static final class Address extends
//      com.google.protobuf.GeneratedMessage implements
//      // @@protoc_insertion_point(message_implements:com.aaron.hookpractice.generate.Address)
//      AddressOrBuilder {
//  private static final long serialVersionUID = 0L;
//    static {
//      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
//        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
//        /* major= */ 4,
//        /* minor= */ 28,
//        /* patch= */ 2,
//        /* suffix= */ "",
//        Address.class.getName());
//    }
//    // Use Address.newBuilder() to construct.
//    private Address(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
//      super(builder);
//    }
//    private Address() {
//      province_ = "";
//      city_ = "";
//      district_ = "";
//      street_ = "";
//      address_ = "";
//    }
//
//    public static final com.google.protobuf.Descriptors.Descriptor
//        getDescriptor() {
//      return com.aaron.hookpractice.generate.UserOuterClass.internal_static_com_aaron_hookpractice_generate_Address_descriptor;
//    }
//
//    @java.lang.Override
//    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
//        internalGetFieldAccessorTable() {
//      return com.aaron.hookpractice.generate.UserOuterClass.internal_static_com_aaron_hookpractice_generate_Address_fieldAccessorTable
//          .ensureFieldAccessorsInitialized(
//              com.aaron.hookpractice.generate.UserOuterClass.Address.class, com.aaron.hookpractice.generate.UserOuterClass.Address.Builder.class);
//    }
//
//    private int bitField0_;
//    public static final int PROVINCE_FIELD_NUMBER = 1;
//    @SuppressWarnings("serial")
//    private volatile java.lang.Object province_ = "";
//    /**
//     * <code>string province = 1;</code>
//     * @return The province.
//     */
//    @java.lang.Override
//    public java.lang.String getProvince() {
//      java.lang.Object ref = province_;
//      if (ref instanceof java.lang.String) {
//        return (java.lang.String) ref;
//      } else {
//        com.google.protobuf.ByteString bs =
//            (com.google.protobuf.ByteString) ref;
//        java.lang.String s = bs.toStringUtf8();
//        province_ = s;
//        return s;
//      }
//    }
//    /**
//     * <code>string province = 1;</code>
//     * @return The bytes for province.
//     */
//    @java.lang.Override
//    public com.google.protobuf.ByteString
//        getProvinceBytes() {
//      java.lang.Object ref = province_;
//      if (ref instanceof java.lang.String) {
//        com.google.protobuf.ByteString b =
//            com.google.protobuf.ByteString.copyFromUtf8(
//                (java.lang.String) ref);
//        province_ = b;
//        return b;
//      } else {
//        return (com.google.protobuf.ByteString) ref;
//      }
//    }
//
//    public static final int CITY_FIELD_NUMBER = 2;
//    @SuppressWarnings("serial")
//    private volatile java.lang.Object city_ = "";
//    /**
//     * <code>string city = 2;</code>
//     * @return The city.
//     */
//    @java.lang.Override
//    public java.lang.String getCity() {
//      java.lang.Object ref = city_;
//      if (ref instanceof java.lang.String) {
//        return (java.lang.String) ref;
//      } else {
//        com.google.protobuf.ByteString bs =
//            (com.google.protobuf.ByteString) ref;
//        java.lang.String s = bs.toStringUtf8();
//        city_ = s;
//        return s;
//      }
//    }
//    /**
//     * <code>string city = 2;</code>
//     * @return The bytes for city.
//     */
//    @java.lang.Override
//    public com.google.protobuf.ByteString
//        getCityBytes() {
//      java.lang.Object ref = city_;
//      if (ref instanceof java.lang.String) {
//        com.google.protobuf.ByteString b =
//            com.google.protobuf.ByteString.copyFromUtf8(
//                (java.lang.String) ref);
//        city_ = b;
//        return b;
//      } else {
//        return (com.google.protobuf.ByteString) ref;
//      }
//    }
//
//    public static final int DISTRICT_FIELD_NUMBER = 3;
//    @SuppressWarnings("serial")
//    private volatile java.lang.Object district_ = "";
//    /**
//     * <code>optional string district = 3;</code>
//     * @return Whether the district field is set.
//     */
//    @java.lang.Override
//    public boolean hasDistrict() {
//      return ((bitField0_ & 0x00000001) != 0);
//    }
//    /**
//     * <code>optional string district = 3;</code>
//     * @return The district.
//     */
//    @java.lang.Override
//    public java.lang.String getDistrict() {
//      java.lang.Object ref = district_;
//      if (ref instanceof java.lang.String) {
//        return (java.lang.String) ref;
//      } else {
//        com.google.protobuf.ByteString bs =
//            (com.google.protobuf.ByteString) ref;
//        java.lang.String s = bs.toStringUtf8();
//        district_ = s;
//        return s;
//      }
//    }
//    /**
//     * <code>optional string district = 3;</code>
//     * @return The bytes for district.
//     */
//    @java.lang.Override
//    public com.google.protobuf.ByteString
//        getDistrictBytes() {
//      java.lang.Object ref = district_;
//      if (ref instanceof java.lang.String) {
//        com.google.protobuf.ByteString b =
//            com.google.protobuf.ByteString.copyFromUtf8(
//                (java.lang.String) ref);
//        district_ = b;
//        return b;
//      } else {
//        return (com.google.protobuf.ByteString) ref;
//      }
//    }
//
//    public static final int STREET_FIELD_NUMBER = 4;
//    @SuppressWarnings("serial")
//    private volatile java.lang.Object street_ = "";
//    /**
//     * <code>optional string street = 4;</code>
//     * @return Whether the street field is set.
//     */
//    @java.lang.Override
//    public boolean hasStreet() {
//      return ((bitField0_ & 0x00000002) != 0);
//    }
//    /**
//     * <code>optional string street = 4;</code>
//     * @return The street.
//     */
//    @java.lang.Override
//    public java.lang.String getStreet() {
//      java.lang.Object ref = street_;
//      if (ref instanceof java.lang.String) {
//        return (java.lang.String) ref;
//      } else {
//        com.google.protobuf.ByteString bs =
//            (com.google.protobuf.ByteString) ref;
//        java.lang.String s = bs.toStringUtf8();
//        street_ = s;
//        return s;
//      }
//    }
//    /**
//     * <code>optional string street = 4;</code>
//     * @return The bytes for street.
//     */
//    @java.lang.Override
//    public com.google.protobuf.ByteString
//        getStreetBytes() {
//      java.lang.Object ref = street_;
//      if (ref instanceof java.lang.String) {
//        com.google.protobuf.ByteString b =
//            com.google.protobuf.ByteString.copyFromUtf8(
//                (java.lang.String) ref);
//        street_ = b;
//        return b;
//      } else {
//        return (com.google.protobuf.ByteString) ref;
//      }
//    }
//
//    public static final int ADDRESS_FIELD_NUMBER = 5;
//    @SuppressWarnings("serial")
//    private volatile java.lang.Object address_ = "";
//    /**
//     * <code>string address = 5;</code>
//     * @return The address.
//     */
//    @java.lang.Override
//    public java.lang.String getAddress() {
//      java.lang.Object ref = address_;
//      if (ref instanceof java.lang.String) {
//        return (java.lang.String) ref;
//      } else {
//        com.google.protobuf.ByteString bs =
//            (com.google.protobuf.ByteString) ref;
//        java.lang.String s = bs.toStringUtf8();
//        address_ = s;
//        return s;
//      }
//    }
//    /**
//     * <code>string address = 5;</code>
//     * @return The bytes for address.
//     */
//    @java.lang.Override
//    public com.google.protobuf.ByteString
//        getAddressBytes() {
//      java.lang.Object ref = address_;
//      if (ref instanceof java.lang.String) {
//        com.google.protobuf.ByteString b =
//            com.google.protobuf.ByteString.copyFromUtf8(
//                (java.lang.String) ref);
//        address_ = b;
//        return b;
//      } else {
//        return (com.google.protobuf.ByteString) ref;
//      }
//    }
//
//    private byte memoizedIsInitialized = -1;
//    @java.lang.Override
//    public final boolean isInitialized() {
//      byte isInitialized = memoizedIsInitialized;
//      if (isInitialized == 1) return true;
//      if (isInitialized == 0) return false;
//
//      memoizedIsInitialized = 1;
//      return true;
//    }
//
//    @java.lang.Override
//    public void writeTo(com.google.protobuf.CodedOutputStream output)
//                        throws java.io.IOException {
//      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(province_)) {
//        com.google.protobuf.GeneratedMessage.writeString(output, 1, province_);
//      }
//      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(city_)) {
//        com.google.protobuf.GeneratedMessage.writeString(output, 2, city_);
//      }
//      if (((bitField0_ & 0x00000001) != 0)) {
//        com.google.protobuf.GeneratedMessage.writeString(output, 3, district_);
//      }
//      if (((bitField0_ & 0x00000002) != 0)) {
//        com.google.protobuf.GeneratedMessage.writeString(output, 4, street_);
//      }
//      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(address_)) {
//        com.google.protobuf.GeneratedMessage.writeString(output, 5, address_);
//      }
//      getUnknownFields().writeTo(output);
//    }
//
//    @java.lang.Override
//    public int getSerializedSize() {
//      int size = memoizedSize;
//      if (size != -1) return size;
//
//      size = 0;
//      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(province_)) {
//        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, province_);
//      }
//      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(city_)) {
//        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, city_);
//      }
//      if (((bitField0_ & 0x00000001) != 0)) {
//        size += com.google.protobuf.GeneratedMessage.computeStringSize(3, district_);
//      }
//      if (((bitField0_ & 0x00000002) != 0)) {
//        size += com.google.protobuf.GeneratedMessage.computeStringSize(4, street_);
//      }
//      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(address_)) {
//        size += com.google.protobuf.GeneratedMessage.computeStringSize(5, address_);
//      }
//      size += getUnknownFields().getSerializedSize();
//      memoizedSize = size;
//      return size;
//    }
//
//    @java.lang.Override
//    public boolean equals(final java.lang.Object obj) {
//      if (obj == this) {
//       return true;
//      }
//      if (!(obj instanceof com.aaron.hookpractice.generate.UserOuterClass.Address)) {
//        return super.equals(obj);
//      }
//      com.aaron.hookpractice.generate.UserOuterClass.Address other = (com.aaron.hookpractice.generate.UserOuterClass.Address) obj;
//
//      if (!getProvince()
//          .equals(other.getProvince())) return false;
//      if (!getCity()
//          .equals(other.getCity())) return false;
//      if (hasDistrict() != other.hasDistrict()) return false;
//      if (hasDistrict()) {
//        if (!getDistrict()
//            .equals(other.getDistrict())) return false;
//      }
//      if (hasStreet() != other.hasStreet()) return false;
//      if (hasStreet()) {
//        if (!getStreet()
//            .equals(other.getStreet())) return false;
//      }
//      if (!getAddress()
//          .equals(other.getAddress())) return false;
//      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
//      return true;
//    }
//
//    @java.lang.Override
//    public int hashCode() {
//      if (memoizedHashCode != 0) {
//        return memoizedHashCode;
//      }
//      int hash = 41;
//      hash = (19 * hash) + getDescriptor().hashCode();
//      hash = (37 * hash) + PROVINCE_FIELD_NUMBER;
//      hash = (53 * hash) + getProvince().hashCode();
//      hash = (37 * hash) + CITY_FIELD_NUMBER;
//      hash = (53 * hash) + getCity().hashCode();
//      if (hasDistrict()) {
//        hash = (37 * hash) + DISTRICT_FIELD_NUMBER;
//        hash = (53 * hash) + getDistrict().hashCode();
//      }
//      if (hasStreet()) {
//        hash = (37 * hash) + STREET_FIELD_NUMBER;
//        hash = (53 * hash) + getStreet().hashCode();
//      }
//      hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
//      hash = (53 * hash) + getAddress().hashCode();
//      hash = (29 * hash) + getUnknownFields().hashCode();
//      memoizedHashCode = hash;
//      return hash;
//    }
//
//    public static com.aaron.hookpractice.generate.UserOuterClass.Address parseFrom(
//        java.nio.ByteBuffer data)
//        throws com.google.protobuf.InvalidProtocolBufferException {
//      return PARSER.parseFrom(data);
//    }
//    public static com.aaron.hookpractice.generate.UserOuterClass.Address parseFrom(
//        java.nio.ByteBuffer data,
//        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//        throws com.google.protobuf.InvalidProtocolBufferException {
//      return PARSER.parseFrom(data, extensionRegistry);
//    }
//    public static com.aaron.hookpractice.generate.UserOuterClass.Address parseFrom(
//        com.google.protobuf.ByteString data)
//        throws com.google.protobuf.InvalidProtocolBufferException {
//      return PARSER.parseFrom(data);
//    }
//    public static com.aaron.hookpractice.generate.UserOuterClass.Address parseFrom(
//        com.google.protobuf.ByteString data,
//        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//        throws com.google.protobuf.InvalidProtocolBufferException {
//      return PARSER.parseFrom(data, extensionRegistry);
//    }
//    public static com.aaron.hookpractice.generate.UserOuterClass.Address parseFrom(byte[] data)
//        throws com.google.protobuf.InvalidProtocolBufferException {
//      return PARSER.parseFrom(data);
//    }
//    public static com.aaron.hookpractice.generate.UserOuterClass.Address parseFrom(
//        byte[] data,
//        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//        throws com.google.protobuf.InvalidProtocolBufferException {
//      return PARSER.parseFrom(data, extensionRegistry);
//    }
//    public static com.aaron.hookpractice.generate.UserOuterClass.Address parseFrom(java.io.InputStream input)
//        throws java.io.IOException {
//      return com.google.protobuf.GeneratedMessage
//          .parseWithIOException(PARSER, input);
//    }
//    public static com.aaron.hookpractice.generate.UserOuterClass.Address parseFrom(
//        java.io.InputStream input,
//        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//        throws java.io.IOException {
//      return com.google.protobuf.GeneratedMessage
//          .parseWithIOException(PARSER, input, extensionRegistry);
//    }
//
//    public static com.aaron.hookpractice.generate.UserOuterClass.Address parseDelimitedFrom(java.io.InputStream input)
//        throws java.io.IOException {
//      return com.google.protobuf.GeneratedMessage
//          .parseDelimitedWithIOException(PARSER, input);
//    }
//
//    public static com.aaron.hookpractice.generate.UserOuterClass.Address parseDelimitedFrom(
//        java.io.InputStream input,
//        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//        throws java.io.IOException {
//      return com.google.protobuf.GeneratedMessage
//          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
//    }
//    public static com.aaron.hookpractice.generate.UserOuterClass.Address parseFrom(
//        com.google.protobuf.CodedInputStream input)
//        throws java.io.IOException {
//      return com.google.protobuf.GeneratedMessage
//          .parseWithIOException(PARSER, input);
//    }
//    public static com.aaron.hookpractice.generate.UserOuterClass.Address parseFrom(
//        com.google.protobuf.CodedInputStream input,
//        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//        throws java.io.IOException {
//      return com.google.protobuf.GeneratedMessage
//          .parseWithIOException(PARSER, input, extensionRegistry);
//    }
//
//    @java.lang.Override
//    public Builder newBuilderForType() { return newBuilder(); }
//    public static Builder newBuilder() {
//      return DEFAULT_INSTANCE.toBuilder();
//    }
//    public static Builder newBuilder(com.aaron.hookpractice.generate.UserOuterClass.Address prototype) {
//      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
//    }
//    @java.lang.Override
//    public Builder toBuilder() {
//      return this == DEFAULT_INSTANCE
//          ? new Builder() : new Builder().mergeFrom(this);
//    }
//
//    @java.lang.Override
//    protected Builder newBuilderForType(
//        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
//      Builder builder = new Builder(parent);
//      return builder;
//    }
//    /**
//     * Protobuf type {@code com.aaron.hookpractice.generate.Address}
//     */
//    public static final class Builder extends
//        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
//        // @@protoc_insertion_point(builder_implements:com.aaron.hookpractice.generate.Address)
//        com.aaron.hookpractice.generate.UserOuterClass.AddressOrBuilder {
//      public static final com.google.protobuf.Descriptors.Descriptor
//          getDescriptor() {
//        return com.aaron.hookpractice.generate.UserOuterClass.internal_static_com_aaron_hookpractice_generate_Address_descriptor;
//      }
//
//      @java.lang.Override
//      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
//          internalGetFieldAccessorTable() {
//        return com.aaron.hookpractice.generate.UserOuterClass.internal_static_com_aaron_hookpractice_generate_Address_fieldAccessorTable
//            .ensureFieldAccessorsInitialized(
//                com.aaron.hookpractice.generate.UserOuterClass.Address.class, com.aaron.hookpractice.generate.UserOuterClass.Address.Builder.class);
//      }
//
//      // Construct using com.aaron.hookpractice.generate.UserOuterClass.Address.newBuilder()
//      private Builder() {
//
//      }
//
//      private Builder(
//          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
//        super(parent);
//
//      }
//      @java.lang.Override
//      public Builder clear() {
//        super.clear();
//        bitField0_ = 0;
//        province_ = "";
//        city_ = "";
//        district_ = "";
//        street_ = "";
//        address_ = "";
//        return this;
//      }
//
//      @java.lang.Override
//      public com.google.protobuf.Descriptors.Descriptor
//          getDescriptorForType() {
//        return com.aaron.hookpractice.generate.UserOuterClass.internal_static_com_aaron_hookpractice_generate_Address_descriptor;
//      }
//
//      @java.lang.Override
//      public com.aaron.hookpractice.generate.UserOuterClass.Address getDefaultInstanceForType() {
//        return com.aaron.hookpractice.generate.UserOuterClass.Address.getDefaultInstance();
//      }
//
//      @java.lang.Override
//      public com.aaron.hookpractice.generate.UserOuterClass.Address build() {
//        com.aaron.hookpractice.generate.UserOuterClass.Address result = buildPartial();
//        if (!result.isInitialized()) {
//          throw newUninitializedMessageException(result);
//        }
//        return result;
//      }
//
//      @java.lang.Override
//      public com.aaron.hookpractice.generate.UserOuterClass.Address buildPartial() {
//        com.aaron.hookpractice.generate.UserOuterClass.Address result = new com.aaron.hookpractice.generate.UserOuterClass.Address(this);
//        if (bitField0_ != 0) { buildPartial0(result); }
//        onBuilt();
//        return result;
//      }
//
//      private void buildPartial0(com.aaron.hookpractice.generate.UserOuterClass.Address result) {
//        int from_bitField0_ = bitField0_;
//        if (((from_bitField0_ & 0x00000001) != 0)) {
//          result.province_ = province_;
//        }
//        if (((from_bitField0_ & 0x00000002) != 0)) {
//          result.city_ = city_;
//        }
//        int to_bitField0_ = 0;
//        if (((from_bitField0_ & 0x00000004) != 0)) {
//          result.district_ = district_;
//          to_bitField0_ |= 0x00000001;
//        }
//        if (((from_bitField0_ & 0x00000008) != 0)) {
//          result.street_ = street_;
//          to_bitField0_ |= 0x00000002;
//        }
//        if (((from_bitField0_ & 0x00000010) != 0)) {
//          result.address_ = address_;
//        }
//        result.bitField0_ |= to_bitField0_;
//      }
//
//      @java.lang.Override
//      public Builder mergeFrom(com.google.protobuf.Message other) {
//        if (other instanceof com.aaron.hookpractice.generate.UserOuterClass.Address) {
//          return mergeFrom((com.aaron.hookpractice.generate.UserOuterClass.Address)other);
//        } else {
//          super.mergeFrom(other);
//          return this;
//        }
//      }
//
//      public Builder mergeFrom(com.aaron.hookpractice.generate.UserOuterClass.Address other) {
//        if (other == com.aaron.hookpractice.generate.UserOuterClass.Address.getDefaultInstance()) return this;
//        if (!other.getProvince().isEmpty()) {
//          province_ = other.province_;
//          bitField0_ |= 0x00000001;
//          onChanged();
//        }
//        if (!other.getCity().isEmpty()) {
//          city_ = other.city_;
//          bitField0_ |= 0x00000002;
//          onChanged();
//        }
//        if (other.hasDistrict()) {
//          district_ = other.district_;
//          bitField0_ |= 0x00000004;
//          onChanged();
//        }
//        if (other.hasStreet()) {
//          street_ = other.street_;
//          bitField0_ |= 0x00000008;
//          onChanged();
//        }
//        if (!other.getAddress().isEmpty()) {
//          address_ = other.address_;
//          bitField0_ |= 0x00000010;
//          onChanged();
//        }
//        this.mergeUnknownFields(other.getUnknownFields());
//        onChanged();
//        return this;
//      }
//
//      @java.lang.Override
//      public final boolean isInitialized() {
//        return true;
//      }
//
//      @java.lang.Override
//      public Builder mergeFrom(
//          com.google.protobuf.CodedInputStream input,
//          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//          throws java.io.IOException {
//        if (extensionRegistry == null) {
//          throw new java.lang.NullPointerException();
//        }
//        try {
//          boolean done = false;
//          while (!done) {
//            int tag = input.readTag();
//            switch (tag) {
//              case 0:
//                done = true;
//                break;
//              case 10: {
//                province_ = input.readStringRequireUtf8();
//                bitField0_ |= 0x00000001;
//                break;
//              } // case 10
//              case 18: {
//                city_ = input.readStringRequireUtf8();
//                bitField0_ |= 0x00000002;
//                break;
//              } // case 18
//              case 26: {
//                district_ = input.readStringRequireUtf8();
//                bitField0_ |= 0x00000004;
//                break;
//              } // case 26
//              case 34: {
//                street_ = input.readStringRequireUtf8();
//                bitField0_ |= 0x00000008;
//                break;
//              } // case 34
//              case 42: {
//                address_ = input.readStringRequireUtf8();
//                bitField0_ |= 0x00000010;
//                break;
//              } // case 42
//              default: {
//                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
//                  done = true; // was an endgroup tag
//                }
//                break;
//              } // default:
//            } // switch (tag)
//          } // while (!done)
//        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
//          throw e.unwrapIOException();
//        } finally {
//          onChanged();
//        } // finally
//        return this;
//      }
//      private int bitField0_;
//
//      private java.lang.Object province_ = "";
//      /**
//       * <code>string province = 1;</code>
//       * @return The province.
//       */
//      public java.lang.String getProvince() {
//        java.lang.Object ref = province_;
//        if (!(ref instanceof java.lang.String)) {
//          com.google.protobuf.ByteString bs =
//              (com.google.protobuf.ByteString) ref;
//          java.lang.String s = bs.toStringUtf8();
//          province_ = s;
//          return s;
//        } else {
//          return (java.lang.String) ref;
//        }
//      }
//      /**
//       * <code>string province = 1;</code>
//       * @return The bytes for province.
//       */
//      public com.google.protobuf.ByteString
//          getProvinceBytes() {
//        java.lang.Object ref = province_;
//        if (ref instanceof String) {
//          com.google.protobuf.ByteString b =
//              com.google.protobuf.ByteString.copyFromUtf8(
//                  (java.lang.String) ref);
//          province_ = b;
//          return b;
//        } else {
//          return (com.google.protobuf.ByteString) ref;
//        }
//      }
//      /**
//       * <code>string province = 1;</code>
//       * @param value The province to set.
//       * @return This builder for chaining.
//       */
//      public Builder setProvince(
//          java.lang.String value) {
//        if (value == null) { throw new NullPointerException(); }
//        province_ = value;
//        bitField0_ |= 0x00000001;
//        onChanged();
//        return this;
//      }
//      /**
//       * <code>string province = 1;</code>
//       * @return This builder for chaining.
//       */
//      public Builder clearProvince() {
//        province_ = getDefaultInstance().getProvince();
//        bitField0_ = (bitField0_ & ~0x00000001);
//        onChanged();
//        return this;
//      }
//      /**
//       * <code>string province = 1;</code>
//       * @param value The bytes for province to set.
//       * @return This builder for chaining.
//       */
//      public Builder setProvinceBytes(
//          com.google.protobuf.ByteString value) {
//        if (value == null) { throw new NullPointerException(); }
//        checkByteStringIsUtf8(value);
//        province_ = value;
//        bitField0_ |= 0x00000001;
//        onChanged();
//        return this;
//      }
//
//      private java.lang.Object city_ = "";
//      /**
//       * <code>string city = 2;</code>
//       * @return The city.
//       */
//      public java.lang.String getCity() {
//        java.lang.Object ref = city_;
//        if (!(ref instanceof java.lang.String)) {
//          com.google.protobuf.ByteString bs =
//              (com.google.protobuf.ByteString) ref;
//          java.lang.String s = bs.toStringUtf8();
//          city_ = s;
//          return s;
//        } else {
//          return (java.lang.String) ref;
//        }
//      }
//      /**
//       * <code>string city = 2;</code>
//       * @return The bytes for city.
//       */
//      public com.google.protobuf.ByteString
//          getCityBytes() {
//        java.lang.Object ref = city_;
//        if (ref instanceof String) {
//          com.google.protobuf.ByteString b =
//              com.google.protobuf.ByteString.copyFromUtf8(
//                  (java.lang.String) ref);
//          city_ = b;
//          return b;
//        } else {
//          return (com.google.protobuf.ByteString) ref;
//        }
//      }
//      /**
//       * <code>string city = 2;</code>
//       * @param value The city to set.
//       * @return This builder for chaining.
//       */
//      public Builder setCity(
//          java.lang.String value) {
//        if (value == null) { throw new NullPointerException(); }
//        city_ = value;
//        bitField0_ |= 0x00000002;
//        onChanged();
//        return this;
//      }
//      /**
//       * <code>string city = 2;</code>
//       * @return This builder for chaining.
//       */
//      public Builder clearCity() {
//        city_ = getDefaultInstance().getCity();
//        bitField0_ = (bitField0_ & ~0x00000002);
//        onChanged();
//        return this;
//      }
//      /**
//       * <code>string city = 2;</code>
//       * @param value The bytes for city to set.
//       * @return This builder for chaining.
//       */
//      public Builder setCityBytes(
//          com.google.protobuf.ByteString value) {
//        if (value == null) { throw new NullPointerException(); }
//        checkByteStringIsUtf8(value);
//        city_ = value;
//        bitField0_ |= 0x00000002;
//        onChanged();
//        return this;
//      }
//
//      private java.lang.Object district_ = "";
//      /**
//       * <code>optional string district = 3;</code>
//       * @return Whether the district field is set.
//       */
//      public boolean hasDistrict() {
//        return ((bitField0_ & 0x00000004) != 0);
//      }
//      /**
//       * <code>optional string district = 3;</code>
//       * @return The district.
//       */
//      public java.lang.String getDistrict() {
//        java.lang.Object ref = district_;
//        if (!(ref instanceof java.lang.String)) {
//          com.google.protobuf.ByteString bs =
//              (com.google.protobuf.ByteString) ref;
//          java.lang.String s = bs.toStringUtf8();
//          district_ = s;
//          return s;
//        } else {
//          return (java.lang.String) ref;
//        }
//      }
//      /**
//       * <code>optional string district = 3;</code>
//       * @return The bytes for district.
//       */
//      public com.google.protobuf.ByteString
//          getDistrictBytes() {
//        java.lang.Object ref = district_;
//        if (ref instanceof String) {
//          com.google.protobuf.ByteString b =
//              com.google.protobuf.ByteString.copyFromUtf8(
//                  (java.lang.String) ref);
//          district_ = b;
//          return b;
//        } else {
//          return (com.google.protobuf.ByteString) ref;
//        }
//      }
//      /**
//       * <code>optional string district = 3;</code>
//       * @param value The district to set.
//       * @return This builder for chaining.
//       */
//      public Builder setDistrict(
//          java.lang.String value) {
//        if (value == null) { throw new NullPointerException(); }
//        district_ = value;
//        bitField0_ |= 0x00000004;
//        onChanged();
//        return this;
//      }
//      /**
//       * <code>optional string district = 3;</code>
//       * @return This builder for chaining.
//       */
//      public Builder clearDistrict() {
//        district_ = getDefaultInstance().getDistrict();
//        bitField0_ = (bitField0_ & ~0x00000004);
//        onChanged();
//        return this;
//      }
//      /**
//       * <code>optional string district = 3;</code>
//       * @param value The bytes for district to set.
//       * @return This builder for chaining.
//       */
//      public Builder setDistrictBytes(
//          com.google.protobuf.ByteString value) {
//        if (value == null) { throw new NullPointerException(); }
//        checkByteStringIsUtf8(value);
//        district_ = value;
//        bitField0_ |= 0x00000004;
//        onChanged();
//        return this;
//      }
//
//      private java.lang.Object street_ = "";
//      /**
//       * <code>optional string street = 4;</code>
//       * @return Whether the street field is set.
//       */
//      public boolean hasStreet() {
//        return ((bitField0_ & 0x00000008) != 0);
//      }
//      /**
//       * <code>optional string street = 4;</code>
//       * @return The street.
//       */
//      public java.lang.String getStreet() {
//        java.lang.Object ref = street_;
//        if (!(ref instanceof java.lang.String)) {
//          com.google.protobuf.ByteString bs =
//              (com.google.protobuf.ByteString) ref;
//          java.lang.String s = bs.toStringUtf8();
//          street_ = s;
//          return s;
//        } else {
//          return (java.lang.String) ref;
//        }
//      }
//      /**
//       * <code>optional string street = 4;</code>
//       * @return The bytes for street.
//       */
//      public com.google.protobuf.ByteString
//          getStreetBytes() {
//        java.lang.Object ref = street_;
//        if (ref instanceof String) {
//          com.google.protobuf.ByteString b =
//              com.google.protobuf.ByteString.copyFromUtf8(
//                  (java.lang.String) ref);
//          street_ = b;
//          return b;
//        } else {
//          return (com.google.protobuf.ByteString) ref;
//        }
//      }
//      /**
//       * <code>optional string street = 4;</code>
//       * @param value The street to set.
//       * @return This builder for chaining.
//       */
//      public Builder setStreet(
//          java.lang.String value) {
//        if (value == null) { throw new NullPointerException(); }
//        street_ = value;
//        bitField0_ |= 0x00000008;
//        onChanged();
//        return this;
//      }
//      /**
//       * <code>optional string street = 4;</code>
//       * @return This builder for chaining.
//       */
//      public Builder clearStreet() {
//        street_ = getDefaultInstance().getStreet();
//        bitField0_ = (bitField0_ & ~0x00000008);
//        onChanged();
//        return this;
//      }
//      /**
//       * <code>optional string street = 4;</code>
//       * @param value The bytes for street to set.
//       * @return This builder for chaining.
//       */
//      public Builder setStreetBytes(
//          com.google.protobuf.ByteString value) {
//        if (value == null) { throw new NullPointerException(); }
//        checkByteStringIsUtf8(value);
//        street_ = value;
//        bitField0_ |= 0x00000008;
//        onChanged();
//        return this;
//      }
//
//      private java.lang.Object address_ = "";
//      /**
//       * <code>string address = 5;</code>
//       * @return The address.
//       */
//      public java.lang.String getAddress() {
//        java.lang.Object ref = address_;
//        if (!(ref instanceof java.lang.String)) {
//          com.google.protobuf.ByteString bs =
//              (com.google.protobuf.ByteString) ref;
//          java.lang.String s = bs.toStringUtf8();
//          address_ = s;
//          return s;
//        } else {
//          return (java.lang.String) ref;
//        }
//      }
//      /**
//       * <code>string address = 5;</code>
//       * @return The bytes for address.
//       */
//      public com.google.protobuf.ByteString
//          getAddressBytes() {
//        java.lang.Object ref = address_;
//        if (ref instanceof String) {
//          com.google.protobuf.ByteString b =
//              com.google.protobuf.ByteString.copyFromUtf8(
//                  (java.lang.String) ref);
//          address_ = b;
//          return b;
//        } else {
//          return (com.google.protobuf.ByteString) ref;
//        }
//      }
//      /**
//       * <code>string address = 5;</code>
//       * @param value The address to set.
//       * @return This builder for chaining.
//       */
//      public Builder setAddress(
//          java.lang.String value) {
//        if (value == null) { throw new NullPointerException(); }
//        address_ = value;
//        bitField0_ |= 0x00000010;
//        onChanged();
//        return this;
//      }
//      /**
//       * <code>string address = 5;</code>
//       * @return This builder for chaining.
//       */
//      public Builder clearAddress() {
//        address_ = getDefaultInstance().getAddress();
//        bitField0_ = (bitField0_ & ~0x00000010);
//        onChanged();
//        return this;
//      }
//      /**
//       * <code>string address = 5;</code>
//       * @param value The bytes for address to set.
//       * @return This builder for chaining.
//       */
//      public Builder setAddressBytes(
//          com.google.protobuf.ByteString value) {
//        if (value == null) { throw new NullPointerException(); }
//        checkByteStringIsUtf8(value);
//        address_ = value;
//        bitField0_ |= 0x00000010;
//        onChanged();
//        return this;
//      }
//
//      // @@protoc_insertion_point(builder_scope:com.aaron.hookpractice.generate.Address)
//    }
//
//    // @@protoc_insertion_point(class_scope:com.aaron.hookpractice.generate.Address)
//    private static final com.aaron.hookpractice.generate.UserOuterClass.Address DEFAULT_INSTANCE;
//    static {
//      DEFAULT_INSTANCE = new com.aaron.hookpractice.generate.UserOuterClass.Address();
//    }
//
//    public static com.aaron.hookpractice.generate.UserOuterClass.Address getDefaultInstance() {
//      return DEFAULT_INSTANCE;
//    }
//
//    private static final com.google.protobuf.Parser<Address>
//        PARSER = new com.google.protobuf.AbstractParser<Address>() {
//      @java.lang.Override
//      public Address parsePartialFrom(
//          com.google.protobuf.CodedInputStream input,
//          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//          throws com.google.protobuf.InvalidProtocolBufferException {
//        Builder builder = newBuilder();
//        try {
//          builder.mergeFrom(input, extensionRegistry);
//        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
//          throw e.setUnfinishedMessage(builder.buildPartial());
//        } catch (com.google.protobuf.UninitializedMessageException e) {
//          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
//        } catch (java.io.IOException e) {
//          throw new com.google.protobuf.InvalidProtocolBufferException(e)
//              .setUnfinishedMessage(builder.buildPartial());
//        }
//        return builder.buildPartial();
//      }
//    };
//
//    public static com.google.protobuf.Parser<Address> parser() {
//      return PARSER;
//    }
//
//    @java.lang.Override
//    public com.google.protobuf.Parser<Address> getParserForType() {
//      return PARSER;
//    }
//
//    @java.lang.Override
//    public com.aaron.hookpractice.generate.UserOuterClass.Address getDefaultInstanceForType() {
//      return DEFAULT_INSTANCE;
//    }
//
//  }
//
//  private static final com.google.protobuf.Descriptors.Descriptor
//    internal_static_com_aaron_hookpractice_generate_User_descriptor;
//  private static final
//    com.google.protobuf.GeneratedMessage.FieldAccessorTable
//      internal_static_com_aaron_hookpractice_generate_User_fieldAccessorTable;
//  private static final com.google.protobuf.Descriptors.Descriptor
//    internal_static_com_aaron_hookpractice_generate_Address_descriptor;
//  private static final
//    com.google.protobuf.GeneratedMessage.FieldAccessorTable
//      internal_static_com_aaron_hookpractice_generate_Address_fieldAccessorTable;
//
//  public static com.google.protobuf.Descriptors.FileDescriptor
//      getDescriptor() {
//    return descriptor;
//  }
//  private static  com.google.protobuf.Descriptors.FileDescriptor
//      descriptor;
//  static {
//    java.lang.String[] descriptorData = {
//      "\n=app/src/main/java/com/aaron/hookpracti" +
//      "ce/protocbuf/user.proto\022\037com.aaron.hookp" +
//      "ractice.generate\"\265\001\n\004User\022\n\n\002id\030\001 \001(\003\022\014\n" +
//      "\004name\030\002 \001(\t\022<\n\006gender\030\003 \001(\0162\'.com.aaron." +
//      "hookpractice.generate.GenderH\000\210\001\001\022>\n\007add" +
//      "ress\030\004 \001(\0132(.com.aaron.hookpractice.gene" +
//      "rate.AddressH\001\210\001\001B\t\n\007_genderB\n\n\010_address" +
//      "\"~\n\007Address\022\020\n\010province\030\001 \001(\t\022\014\n\004city\030\002 " +
//      "\001(\t\022\025\n\010district\030\003 \001(\tH\000\210\001\001\022\023\n\006street\030\004 \001" +
//      "(\tH\001\210\001\001\022\017\n\007address\030\005 \001(\tB\013\n\t_districtB\t\n" +
//      "\007_street*\036\n\006Gender\022\010\n\004Male\020\000\022\n\n\006Female\020\001" +
//      "b\006proto3"
//    };
//    descriptor = com.google.protobuf.Descriptors.FileDescriptor
//      .internalBuildGeneratedFileFrom(descriptorData,
//        new com.google.protobuf.Descriptors.FileDescriptor[] {
//        });
//    internal_static_com_aaron_hookpractice_generate_User_descriptor =
//      getDescriptor().getMessageTypes().get(0);
//    internal_static_com_aaron_hookpractice_generate_User_fieldAccessorTable = new
//      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
//        internal_static_com_aaron_hookpractice_generate_User_descriptor,
//        new java.lang.String[] { "Id", "Name", "Gender", "Address", });
//    internal_static_com_aaron_hookpractice_generate_Address_descriptor =
//      getDescriptor().getMessageTypes().get(1);
//    internal_static_com_aaron_hookpractice_generate_Address_fieldAccessorTable = new
//      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
//        internal_static_com_aaron_hookpractice_generate_Address_descriptor,
//        new java.lang.String[] { "Province", "City", "District", "Street", "Address", });
//    descriptor.resolveAllFeaturesImmutable();
//  }
//
//  // @@protoc_insertion_point(outer_class_scope)
//}
